# Generated by Django 3.0.4 on 2020-03-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
