# Generated by Django 3.0.4 on 2020-03-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200326_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirp',
            options={},
        ),
    ]
