# Generated by Django 3.0.4 on 2020-03-26 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200326_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirp',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='chirp',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 22, 17, 46, 333082, tzinfo=utc)),
        ),
    ]
